import Foundation

@main
struct AppRegressionSmoke {
    static func main() async throws {
        try await SVNSafetyRegressionChecks.run()
#if !SVNDOCK_SAFETY_SMOKE
        try await FileRestoreRegressionChecks.run()
        try StatusTreeRegressionChecks.run()
        try await IgnoreRecommendationRegressionChecks.run()
        try await CommitDraftRegressionChecks.run()
        try await SelectedCommitRegressionChecks.run()
        try await ServiceProgressRegressionChecks.run()
        try await StoreProgressRegressionChecks.run()
        try await LargeAdditionRegressionChecks.run()
        try await LargeDirectoryDeletionRegressionChecks.run()
        try await LargeDiffPresentationRegressionChecks.run()
        try await LocalDifferenceRegressionChecks.run()
        try await DifferenceFilterStoreRegressionChecks.run()
        try ReviewInteractionRegressionChecks.localPreviewBoundaries()
        try ReviewInteractionRegressionChecks.contextSelectionPreservesScope()
        try WorkingCopyStatusRegressionChecks.run()
        try await RemoteStoreRegressionChecks.run()
        try OperationRecordRegressionChecks.run()
        try await OperationStoreRegressionChecks.run()
        try await ConflictReviewRegressionChecks.run()
        try await ResolveServiceRegressionChecks.run()
        try await IgnoredItemsRegressionChecks.run()
        try await IgnoredItemsStoreRegressionChecks.run()
        try await FinderRoutingRegressionChecks.run()
        try await FinderBadgeServiceRegressionChecks.run()
        try HistoryQueryRegressionChecks.run()
        try await HistoryPagingRegressionChecks.run()
        try await HistoryPageServiceRegressionChecks.run()
        try await HistoryRevisionServiceRegressionChecks.run()
        try await StoreRegressionChecks.failedStatusCannotAppearCleanOrRetainActions()
        try await StoreRegressionChecks.selectionCancelsDiff()
        try await StoreRegressionChecks.directoryRetryRejectsOldError()
        try await MissingDeletionRegressionChecks.run()
        try await MissingStatusRegressionChecks.run()
        try await MissingRevertRegressionChecks.run()
        try await RegistrationRegressionChecks.run()
        try await PreferencesRegressionChecks.run()
        try await MenuBarStoreRegressionChecks.run()
        try ViewsRegressionChecks.snapshotStorageAndGrouping()
        try ViewsRegressionChecks.diffPresentationPreservesRows()
        try await ViewsRegressionChecks.clearedDiffDiscardsPresentation()
        try await ViewsRegressionChecks.historySelectionAndFiltering()
        try await ViewsRegressionChecks.historyDiffCacheRetainsRecentlyUsedEntries()
        print("App regression checks passed")
#endif
    }
}
